// This file is auto-generated by @hey-api/openapi-ts

export const $User = {
    type: 'object',
    required: ['id', 'first_name', 'last_name'],
    properties: {
        first_name: {
            type: 'string'
        },
        last_name: {
            type: 'string'
        },
        id: {
            type: 'number'
        }
    }
} as const;