// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { GetApiV1UsersByUserIdData, GetApiV1UsersByUserIdError, GetApiV1UsersByUserIdResponse, GetApiV1UsersError, GetApiV1UsersResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get a user by their ID
 */
export const getApiV1UsersByUserId = (options: Options<GetApiV1UsersByUserIdData>) => { return (options?.client ?? client).get<GetApiV1UsersByUserIdResponse, GetApiV1UsersByUserIdError>({
    ...options,
    url: '/api/v1/users/{userId}'
}); };

/**
 * Returns a list of users.
 */
export const getApiV1Users = (options?: Options) => { return (options?.client ?? client).get<GetApiV1UsersResponse, GetApiV1UsersError>({
    ...options,
    url: '/api/v1/users'
}); };