openapi: 3.0.0 # express-openapi-validator is moving to support 3.1.0 soon, see: https://github.com/cdimascio/express-openapi-validator/pull/882
info:
  title: Typescript Full Stack OpenAPI Template
  version: 0.0.1
paths:
  /api/v1/users/{userId}:
    get:
      summary: Get a user by their ID
      parameters:
      - in: path
        name: userId
        schema:
          type: integer
        required: true
        description: Numeric ID of the user
      responses:
        '200':
          description: A JSON object of a single user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/v1/users:
    get:
      summary: Returns a list of users.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - first_name
        - last_name
      properties:
        first_name:
          type: string
        last_name:
          type: string
        id:
          type: number

